image: docker:git
services:
    - docker:dind

stages:
  - test
  - build
  - deploy

teste-app:
  stage: test
  image: python:3.9.10-slim-bullseye
  services:
      - docker:dind
  script:
      - apt update && apt install -y python3-mysqldb libmariadb-dev gcc
      - pip install -r requirements.txt
      - nosetests --with-xunit --with-coverage --cover-package=project test_users.py"