image: docker:git
services:
    - docker:dind

stages:
  - test
  - build
  - deploy

teste-app:
  stage: test
  image: python:3.9.10-slim-bullseye
  services:
      - docker:dind
  script:
      - apt update && apt install -y python3-mysqldb libmariadb-dev gcc
      - pip install -r requirements.txt
      - nosetests --with-xunit --with-coverage --cover-package=project test_users.py
  artifacts:
    when: always
    paths:
      - nosetests.xml
    reports:
      junit: nosetests.xml

build:
  stage: build
  dependencies:
    - teste-app
  services:
      - docker:dind
  script:
      - docker login -u gitlab-ci-token -p "$CI_JOB_TOKEN" "$CI_REGISTRY"
      - docker build -t ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA} .
      - docker push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}


include:
  - template: Jobs/SAST.gitlab-ci.yml

spotbugs-sast:
  variables:
    FAIL_NEVER: 1