name: Container Image build

on:
  push:
    branches:
     - master
  schedule:
    - cron: '0 1 * * *'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: simplepythonflask

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Login REGISTRY
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY}}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extrair Metadados
        id: metadado
        uses: docker/metadata-action@v5
        with:
          image: ${{ env.REGISTRY}}/${{ github.repository_owner }}/${{ env.IMAGE_NAME}}
      - name: "Build Image"
        run: docker build . --file Dockerfile --tag ${{ env.REGISTRY}}/odilhao/${{ env.IMAGE_NAME}}
      - name: "Push Image"
        run: docker push ${{ env.REGISTRY}}/odilhao/${{ env.IMAGE_NAME}}